export const FETCH_FILMS_SEARCH_SUCCES = 'FETCH_FILMS_SEARCH_SUCCES';
export const FETCH_FILMS_SEARCH_FAIL = 'FETCH_FILMS_SEARCH_FAIL';
export const FETCH_FILMS_SEARCH_REFRESH = 'FETCH_FILMS_SEARCH_REFRESH';